version: '3'

services:

  redis:
    image: redis
    ports:
      - '6385:6379'
    expose:
      - '6385'
    networks:
      - shop


  db:
    container_name: shop_db
    hostname: shop_db
    image: mysql:5.7
    volumes:
      - nest_example_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - shop

  api:
    container_name: api
    hostname: api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - .:/api
    ports:
      - "4000:4000"
    links:
      - redis
    tty: true
    expose:
      - "4000"
    depends_on:
      - redis
      - order
      - payment
    networks:
      - shop

  order:
    container_name: order
    hostname: order
    build:
      context: ./order
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/order
    links:
      - redis
    depends_on:
      - redis
      - db
      - payment
    networks:
      - shop

  payment:
    container_name: payment
    hostname: payment
    build:
      context: ./payment
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/payment
    links:
      - redis
    depends_on:
      - redis
      - db
    networks:
      - shop

volumes:
  nest_example_data:

networks:
  shop:
    driver: bridge
