version: '3'

services:

  db:
    container_name: shop_db
    hostname: shop_db
    image: mysql:5.7
    volumes:
      - nest_example_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - shop

  api:
    container_name: api
    hostname: api
    build: 
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - .:/api
    ports:
      - "4000:4000"
      - "4001:4001"
      - "9222:9222"
    tty: true
    networks:
      - shop
    expose:
      - "4000"
    depends_on:
      - order
      - payment

  order:
    container_name: order
    hostname: order
    build: 
      context: ./order
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/order
    tty: true
    networks:
      - shop
    ports:
      - "4002:4002"
    depends_on:
      - db
      - payment

  payment:
    container_name: payment
    hostname: payment
    build: 
      context: ./payment
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/payment
    tty: true
    networks:
      - shop
    ports:
      - "4003:4003"
    depends_on:
      - db

volumes:
  nest_example_data:

networks: 
  shop:
    driver: bridge
